# root_url = 'http://zq.win007.com/info/index_cn.htm'
root_url = 'http://zq.win007.com/cn/League/36.html'
league_url = 'http://zq.win007.com/jsData/leftData/leftData.js'
# root_url = 'http://www.bet007.com/'
# root_url = 'http://news.baidu.com/'